config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  root to: "home#index"
  get "up" => "rails/health#show", as: :rails_health_check

  post "/users/sign_in" => "users#sign_in", as: "sign_in_user"
  delete "/users/sign_out" => "users#sign_out", as: "sign_out_user"

  get "/users" => "users#index"
  get "/users/new" => "users#new", as: "new_user"
  post "/users" => "users#create", as: "create_user"
  get "/users/:id" => "users#show", as: "user"
  get "/users/:id/edit" => "users#edit", as: "edit_users"
  put "users/:id" => "users#update", as: "update_user"
  patch "users/:id" => "users#update"
  delete "users/:id" => "users#destroy", as: "delete_user"




  get "/categories" => "users#index"
  get "/categories/new" => "categories#new", as: "new_category"
  post "/categories" => "categories#create", as: "create_cat"
  get "/categories/:id" => "categories#show", as: "category"
  get "/categories/:id/edit" => "categories#edit", as: "edit_category"
  put "categories/:id" => "categories#update", as: "update_category"
  patch "categories/:id" => "categories#update"
  delete "categories/:id" => "categories#destroy", as: "delete_category"

  # Nested Task routes
  get "/categories/:category_id/tasks" => "tasks#index", as: "category_tasks"
  get "/categories/:category_id/tasks/new" => "tasks#new", as: "new_category_task"
  post "/categories/:category_id/tasks" => "tasks#create"


  get "/tasks" => "tasks#index"
  get "/tasks/new" => "tasks#new", as: "new_task"
  post "/tasks" => "tasks#create", as: "create_task"
  get "/tasks/:id" => "tasks#show", as: "task"
  get "/tasks/:id/edit" => "tasks#edit", as: "edit_task"
  put "tasks/:id" => "tasks#update", as: "update_task"
  patch "tasks/:id" => "tasks#update"
  delete "/tasks/:id" => "tasks#destroy", as: "delete_task"

  # get "sign_up", "user#new"
  # post "sign_up", to "user#create"



  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
  validates :taskname, presence: true
  validates :details, presence: true#, length: { minimum: 10 }
  validates :duedate, presence: true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_category, only: [ :index, :new, :create ]
  before_action :set_task, only: [ :show, :edit, :update, :destroy ]

  def index
    @tasks = @category.tasks
  end

  def show
  end

  def new
    @task = @category.tasks.new
  end

  def create
    @task = @category.tasks.new(task_params)
    if @task.save
      flash.notice = "New Task added"
      redirect_to category_path(@category)
    else
      puts @task.errors.full_messages
      flash.alert = "Task not saved"
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to category_path(@task.category)
    else
      render :edit
    end
  end

  def destroy
    category = @task.category
    @task.destroy
    redirect_to category_path(category), notice: "Task was successfully deleted."
  end

  private

  def set_category
    @category = Current.user.categories.find(params[:category_id])
  end

  def set_task
    @task = Task.find(params[:id])
    # Ensure the task belongs to a category owned by the current user
    unless Current.user.categories.include?(@task.category)
      redirect_to root_path, alert: "You are not authorized to access this task."
    end
  end

  def task_params
    params.require(:task).permit(:taskname, :details, :duedate)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/edit.html.erb
<%= form_with scope: :task, url: update_task_path, method: :put, local: true do |f| %>
  <p>
    <%= f.label :taskname %><br/>
    <%= f.text_field :taskname %>
  </p>

  <p>
    <%= f.label :details %><br/>
    <%= f.text_field :details %>
  </p>

  <p>
    <%= f.label :duedate %>
    <%= f.date_field :duedate%>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/tasks/index.html.erb
<h1>Hello</h1>

app/views/tasks/new.html.erb

<h2>Create your task</h2>
<p>Create your personalized task and set a due date for a more efficient and balanced day</p>

<%= form_with model: @task, url: create_task_path, local: true do |f| %>
  <%= hidden_field_tag :category_id, @category.id %>
  <%= f.label :taskname %>
  <%= f.text_field :taskname %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :duedate %>
  <%= f.date_field :duedate %>
  <%= f.submit "Create Task" %>
<% end %>

app/views/tasks/show.html.erb
<table>
  <h2>Task Details</h2>
  <tbody>
    <tr>
      <tr><td><strong><%= @task.taskname %></strong></td></tr>
      <tr><td><%= @task.details %></td></tr>
      <tr><td><%= @task.duedate %></td></tr>
    </tr>
  </tbody>
</table>