config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  root to: "home#index"
  get "up" => "rails/health#show", as: :rails_health_check

  post "/users/sign_in" => "users#sign_in", as: "sign_in_user"
  delete "/users/sign_out" => "users#sign_out", as: "sign_out_user"

  get "/users" => "users#index"
  get "/users/new" => "users#new", as: "new_user"
  post "/users" => "users#create", as: "create_user"
  get "/users/:id" => "users#show", as: "user"
  get "/users/:id/edit" => "users#edit", as: "edit_users"
  put "users/:id" => "users#update", as: "update_user"
  patch "users/:id" => "users#update"
  delete "users/:id" => "users#destroy", as: "delete_user"




  get "/categories" => "users#index"
  get "/categories/new" => "categories#new", as: "new_category"
  post "/categories" => "categories#create", as: "create_cat"
  get "/categories/:id" => "categories#show", as: "category"
  get "/categories/:id/edit" => "categories#edit", as: "edit_category"
  put "categories/:id" => "categories#update", as: "update_category"
  patch "categories/:id" => "categories#update"
  delete "categories/:id" => "categories#destroy", as: "delete_category"

  # Nested Task routes
  get "/categories/:category_id/tasks" => "tasks#index", as: "category_tasks"
  get "/categories/:category_id/tasks/new" => "tasks#new", as: "new_category_task"
  post "/categories/:category_id/tasks" => "tasks#create"


  get "/tasks" => "tasks#index"
  get "/tasks/new" => "tasks#new", as: "new_task"
  post "/tasks" => "tasks#create", as: "create_task"
  get "/tasks/:id" => "tasks#show", as: "task"
  get "/tasks/:id/edit" => "tasks#edit", as: "edit_task"
  put "tasks/:id" => "tasks#update", as: "update_task"
  patch "tasks/:id" => "tasks#update"
  delete "/tasks/:id" => "tasks#destroy", as: "delete_task"

  # get "sign_up", "user#new"
  # post "sign_up", to "user#create"



  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :categories
  validates :username, presence: true, uniqueness: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in!, only: [ :index ]

  def index
    @categories = Current.user.categories
    puts "Categories: #{@categories.inspect}"
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash.notice = "Welcome! You are now registered successfully"
      redirect_to root_path
    else
      puts @user.errors.full_messages
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path
    else
      render :edit
    end
  end

  def delete
    @user 
  end

  def sign_in
    @user = User.where(username: params[:user][:username], email: params[:user][:email]).first

    if @user
      session[:user_id] = @user.id
      flash.notice = "Signed in successfully!"
      redirect_to users_path
    else
      flash.alert = "Invalid username or email"
      redirect_to root_path
    end
  end

  def sign_out
    # User.find(session[:user_id]).destroy 
    session[:user_id] = nil
    flash.notice = "You have been signed out."
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def require_user_logged_in!
    redirect_to root_path, alert: "You must be signed in to do that." if Current.user.nil?
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb

<h1>Hello</h1>
<h6><%= link_to 'Create new Category', new_category_path %></h6>
<br>
<thead>
  <th>No.</th>
  <th>Category</th>
  <th>Desc.</th>
</thead>
<br>
<tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.number %></td>
        <td><%= category.note %></td>
        <td><%= category.description %></td>
        <br>
        <td><button><%= link_to 'Show', category_path(category.id) %></button></td>
        <td><button><%= link_to 'Edit', edit_category_path(category.id)%></button></td>
        <td><%= button_to 'Delete', delete_category_path(category.id), method: :delete %></td>
      </tr>
    <% end %>
</tbody>

<%= link_to 'Log out', root_path %>

app/views/users/new.html.erb
<div class="container">

 <div class="row justify-content-center">

   <div class="col-5">

     <div class="mt-3">

       <h1> Sign Up </h1>

     </div>

     <%= form_with model: @user, url: create_user_path, method: :post do |f| %>

        <div class="form-group row mt-3">

          <%= f.label :email, "Email" %>

          <%= f.text_field :email, class: "form-control",

                   placeholder: "Enter your email address" %>

        </div>

        <div class="form-group row mt-3">

          <%= f.label :username, "Username"%>

          <%= f.text_field :username, class: "form-control",

                                placeholder: "Enter your Username" %>

        </div>

        <div class=" form-group row mt-3">

         <%= f.submit "Sign Up", class: "btn btn-primary" %>

        </div>

     <% end %>

   </div>

 </div>

</div>