config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  root to: "home#index"
  get "up" => "rails/health#show", as: :rails_health_check

  post "/users/sign_in" => "users#sign_in", as: "sign_in_user"
  delete "/users/sign_out" => "users#sign_out", as: "sign_out_user"

  get "/users" => "users#index"
  get "/users/new" => "users#new", as: "new_user"
  post "/users" => "users#create", as: "create_user"
  get "/users/:id" => "users#show", as: "user"
  get "/users/:id/edit" => "users#edit", as: "edit_users"
  put "users/:id" => "users#update", as: "update_user"
  patch "users/:id" => "users#update"
  delete "users/:id" => "users#destroy", as: "delete_user"




  get "/categories" => "users#index"
  get "/categories/new" => "categories#new", as: "new_category"
  post "/categories" => "categories#create", as: "create_cat"
  get "/categories/:id" => "categories#show", as: "category"
  get "/categories/:id/edit" => "categories#edit", as: "edit_category"
  put "categories/:id" => "categories#update", as: "update_category"
  patch "categories/:id" => "categories#update"
  delete "categories/:id" => "categories#destroy", as: "delete_category"

  # Nested Task routes
  get "/categories/:category_id/tasks" => "tasks#index", as: "category_tasks"
  get "/categories/:category_id/tasks/new" => "tasks#new", as: "new_category_task"
  post "/categories/:category_id/tasks" => "tasks#create"


  get "/tasks" => "tasks#index"
  get "/tasks/new" => "tasks#new", as: "new_task"
  post "/tasks" => "tasks#create", as: "create_task"
  get "/tasks/:id" => "tasks#show", as: "task"
  get "/tasks/:id/edit" => "tasks#edit", as: "edit_task"
  put "tasks/:id" => "tasks#update", as: "update_task"
  patch "tasks/:id" => "tasks#update"
  delete "/tasks/:id" => "tasks#destroy", as: "delete_task"

  # get "sign_up", "user#new"
  # post "sign_up", to "user#create"



  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = User.order(:id)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Welcome to LIFE</h1>
<p>(your personal journal and task organizer)</p>

<%= form_with model: @user, url: sign_in_user_path, local: true do |f|%>
  <div class="form-group row mt-3">

    <%= f.label :email, "Email" %>

          <%= f.text_field :email, class: "form-control",

                   placeholder: "Enter your email address" %>

  </div>

  <div class="form-group row mt-3">

          <%= f.label :username, "Username"%>

          <%= f.text_field :username, class: "form-control",

                      placeholder: "Enter your Username" %>

  </div>
  <div class=" form-group row mt-3">

  <div class="form-group row mt-3">
    <%= f.submit "Log In", class: "btn btn-primary" %>

  </div>

<% end %>

<br>
<%= link_to 'Register', new_user_path, class: 'btn btn-primary'%>
