config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  root to: "home#index"
  get "up" => "rails/health#show", as: :rails_health_check

  post "/users/sign_in" => "users#sign_in", as: "sign_in_user"
  delete "/users/sign_out" => "users#sign_out", as: "sign_out_user"

  get "/users" => "users#index"
  get "/users/new" => "users#new", as: "new_user"
  post "/users" => "users#create", as: "create_user"
  get "/users/:id" => "users#show", as: "user"
  get "/users/:id/edit" => "users#edit", as: "edit_users"
  put "users/:id" => "users#update", as: "update_user"
  patch "users/:id" => "users#update"
  delete "users/:id" => "users#destroy", as: "delete_user"




  get "/categories" => "users#index"
  get "/categories/new" => "categories#new", as: "new_category"
  post "/categories" => "categories#create", as: "create_cat"
  get "/categories/:id" => "categories#show", as: "category"
  get "/categories/:id/edit" => "categories#edit", as: "edit_category"
  put "categories/:id" => "categories#update", as: "update_category"
  patch "categories/:id" => "categories#update"
  delete "categories/:id" => "categories#destroy", as: "delete_category"

  # Nested Task routes
  get "/categories/:category_id/tasks" => "tasks#index", as: "category_tasks"
  get "/categories/:category_id/tasks/new" => "tasks#new", as: "new_category_task"
  post "/categories/:category_id/tasks" => "tasks#create"


  get "/tasks" => "tasks#index"
  get "/tasks/new" => "tasks#new", as: "new_task"
  post "/tasks" => "tasks#create", as: "create_task"
  get "/tasks/:id" => "tasks#show", as: "task"
  get "/tasks/:id/edit" => "tasks#edit", as: "edit_task"
  put "tasks/:id" => "tasks#update", as: "update_task"
  patch "tasks/:id" => "tasks#update"
  delete "/tasks/:id" => "tasks#destroy", as: "delete_task"

  # get "sign_up", "user#new"
  # post "sign_up", to "user#create"



  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tasks
  belongs_to :user
  validates :note, presence: true#, exclusion: { in: [ nil ] }
  validates :description, presence: true#, length: { minimum: 50 }
  validates :number, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Current.user.categories
  end

  def show
    @category = Current.user.categories.find(params[:id])
    @tasks = @category.tasks
  end

  def new
    @category = Category.new
  end

  def create
    # @user = User.where(signed_in: true).first
    # @category = @user.categories.build(category_params)
    # #puts category_params.inspect
    # #puts @category.inspect
    # #puts @category.valid?
    # if @category.save
    #   flash.notice = "New category has been added"
    #   redirect_to users_path
    # else
    #   flash.alert = "Category was not saved"
    #   render :new
    # end
    @category = Current.user.categories.build(category_params)

    if @category.save
      redirect_to users_path
    else
      render :new
    end
  end

  def edit
    @category = Current.user.categories.find(params[:id])
  end

  def update
    @category = Current.user.categories.find(params[:id])

    if @category.update(category_params)
      redirect_to users_path
    else
      render :edit
    end
  end

  def destroy
    @category = Current.user.categories.find(params[:id])
    @category.destroy
    redirect_to users_path
  end

  def create_category
    @category = Category.where(note: params[:category][:note], description: params[:category][:description], number: params[:category][:number]).first

    if @category
      @category.update(create_category: true)
      flash.notice = "New Category created"
      redirect_to users_path
    else
      flash.alert = "Category not saved"
      redirect_to users_path
    end
  end
  private
  def category_params
    params.require(:category).permit(:user_id, :note, :description, :number)
  end
  def user_params
    params.require(:user).permit(:username, :email)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<%= form_with scope: :category, url: update_category_path, method: :put, local: true do |f| %>

<p>
  <%= f.label :note %><br/>
  <%= f.text_field :note %>
</p>

<p>
  <%= f.label :description %><br/>
  <%= f.text_field :description %>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>

app/views/categories/new.html.erb
<%= form_with model: @category, url: create_cat_path, method: :post do |f |%>

  <div class = "form-group row mt-3">

    <%= f.label :number, "Number" %>
    <%= f.text_field :number, class: "form-control", placeholder: "No." %>,

  </div>

  <div class="form-group row mt-3">

    <%= f.label :note, "Note" %>
    <%= f.text_field :note, class: "form-control", placeholder: "Category name" %>

  </div>

  <div class=" form-group row mt-3">

    <%= f.label :description, "Desc." %>
    <%= f.text_field :description, class: "form-control", placeholder: "Short description" %>

  </div>

  <div class=" form-group row mt-3">
    <%= f.submit "Create Category", class: "btn btn-primary" %>
  </div>

<% end %>

  
    

app/views/categories/show.html.erb
<% if flash.notice %>
  <div class="alert alert-success"><%= flash.notice %></div>
<% end %>
<table>
  <thead>
    <tr>
      <th>No.</th>
      <th>Note</th>
      <th>Description</th>
      <th><%= link_to "Add Task", new_task_path(category_id: @category.id) %></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @category.number %></td>
        <td><%= @category.note %></td>
        <td><%= @category.description %></td>
      </tr>
  </tbody>
</table>
<p><strong>Tasks for <%= @category.note %></strong></p>
  <ul>
    <% @tasks.each do |task| %>
      <li>
        <strong><%= task.taskname %></strong> - <%= task.details %> 
        (Due:
        <% if task.duedate == Date.today %>
          <span style="background-color: orange; color: black; padding: 2px 6px; border-radius: 4px;">
            <%= task.duedate %> (Today)
          </span>
        <% elsif task.duedate < Date.today %>
          <span style="background-color: red; color: white; padding: 2px 6px; border-radius: 4px;">
            <%= task.duedate %> (Past Due)
          </span>
        <% else %>
          <%= task.duedate %>
        <% end %>
      )
      </li>
      <button><%= link_to 'Show Task', task_path(task.id) %></button>
      <button><%= link_to 'Edit Task', edit_task_path(task.id)%></button>
      <%= button_to 'Delete Task', delete_task_path(task.id), method: :delete %>
    <% end %>
  </ul>
<%= link_to "Back", categories_path%>